os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.3beta

addons:
  apt:
    packages:
      - libmariadbclient-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vapor/tap/cmysql; fi

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - sh scripts/compile
